#!/bin/bash
echo "====== Make sure java is in the PATH ======"
if [ -f /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java ]
then
    if [[ ":$PATH:" == *":/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:"* ]]
    then  
        echo "Already there" > /dev/null
    else  
        echo PATH='"$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin"' >> $HOME/.profile
        PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin"
    fi    
else
    if [ -f /usr/lib/jvm/java-8-openjdk-amd64/bin/java ]
    then  
        if [[ ":$PATH:" == *":/usr/lib/jvm/java-8-openjdk-amd64/bin:"* ]]
        then
            echo "Already there" > /dev/null
        else
            echo 'PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/bin"' >> $HOME/.profile
            PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/bin"
        fi
    fi    
fi
cd $HOME
mkdir -p bin
mkdir -p jnk
mkdir -p tmp
mkdir -p files/backups/Vertiv
mkdir -p files/home
mkdir -p files/logs/screen
mkdir -p files/work/Vertiv
mkdir -p files/othersrc
mkdir -p .ssh
chmod 700 .ssh
if [ ! -f .ssh/id_rsa.pub ]
then
    ssh-keygen -t rsa -b 4096
fi
grep -qxF 'set -o vi' $HOME/.bashrc || echo 'set -o vi' >> $HOME/.bashrc
cd $HOME/files/home/edt-env
git config --global core.editor "vim"
git config pull.rebase false
cd $HOME/files/home
for i in edt-btok edt-hp edt-jnk edt-deleteShallow edt-par2win \
    edt-archivedirectory edt-pictures edt-password \
    edt-chess edt-riscv edt-docs edt-bin
do
    if [ ! -d "$i" ]
    then
	git clone "https://github.com/edt11x/$i.git"
    fi
done
if [ ! -f "$HOME/.vimrc" ]
then
    cp -ax edt-jnk/vim/vimrc "$HOME/.vimrc"
fi
if [ ! -d "$HOME/.vim" ]
then
    cp -ax edt-jnk/vim/vim "$HOME/.vim"
fi
if [ -f edt-archivedirectory/archivedirectory ]
then
    cp -ax edt-archivedirectory/archivedirectory "$HOME/bin"
fi

cd $HOME/files/othersrc
if [ ! -d "vim-plug" ]
then
    git clone https://github.com/junegunn/vim-plug.git
fi

# Check if a version of java is in /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
if [ -f /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java ]
then
    # look for it in the path
    if [[ ":$PATH:" == *":/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:"* ]]
    then
        echo "Already there" > /dev/null
    else
        echo 'PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin"' >> ~/.bash_profile
    fi
fi

echo "DIR 01;36" > $HOME/.dir_colors
echo "DIR 01;36" > $HOME/.dircolors
# -q is quiet
# -F is plain string
grep -qF 'LS_COLORS=' $HOME/.bashrc || dircolors -b $HOME/.dir_colors >> $HOME/.bashrc
grep -qF 'alias cde=' $HOME/.bashrc || echo 'alias cde="cd $HOME/files/home/edt-env"' >> $HOME/.bashrc
grep -qF 'alias cdh=' $HOME/.bashrc || echo 'alias cdh="cd $HOME/files/home"' >> $HOME/.bashrc
grep -qF 'alias cdr=' $HOME/.bashrc || echo 'alias cdr="cd $HOME/files/work/Vertiv/realtek-switch-simulator"' >> $HOME/.bashrc
grep -qF 'alias cdv=' $HOME/.bashrc || echo 'alias cdv="cd $HOME/files/work/Vertiv"' >> $HOME/.bashrc
grep -qF 'alias cdw=' $HOME/.bashrc || echo -e 'alias cdw=\047function _cdw() { cd $( dirname $( find . -name "$1" -type f -print -quit )) ; } ; _cdw \047' >> $HOME/.bashrc
grep -qF 'alias cdgen=' $HOME/.bashrc || echo -e 'alias cdgen=\047function _cdgen() { echo -e alias "$1"="\\047cd \\042$( readlink -f $2 )\\042\\047" >> ~/.bashrc ; } ; _cdgen\047' >> $HOME/.bashrc
grep -qF 'alias screen=' $HOME/.bashrc || echo 'alias screen="/usr/bin/screen -L -Logfile ~/files/logs/screen/screen_`date +%y%m%d_%H.%M.%S`.log"' >> $HOME/.bashrc
grep -qF 'alias viw=' $HOME/.bashrc || echo -e 'alias viw=\047function _viw() { vim $( find . -name "$1" -type f -print -quit ) ; } ; _viw \047' >> $HOME/.bashrc
