#!/bin/bash
echo "====== Make sure java is in the PATH ======"
if [ -f /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java ]
then
    if [[ ":$PATH:" == *":/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:"* ]]
    then  
        echo "Already there" > /dev/null
    else  
        echo PATH='"$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin"' >> $HOME/.profile
        PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin"
    fi    
else
    if [ -f /usr/lib/jvm/java-8-openjdk-amd64/bin/java ]
    then  
        if [[ ":$PATH:" == *":/usr/lib/jvm/java-8-openjdk-amd64/bin:"* ]]
        then
            echo "Already there" > /dev/null
        else
            echo 'PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/bin"' >> $HOME/.profile
            PATH="$PATH:/usr/lib/jvm/java-8-openjdk-amd64/bin"
        fi
    fi    
fi
cd $HOME
mkdir -p bin
mkdir -p jnk
mkdir -p tmp
mkdir -p files/home
mkdir -p files/work/Vertiv
mkdir -p files/othersrc
grep -qxF 'set -o vi' $HOME/.bashrc || echo 'set -o vi' >> $HOME/.bashrc
cd $HOME/files/home/edt-env
git config --global core.editor "vim"
git config pull.rebase false
cd $HOME/files/home
for i in edt-btok edt-hp edt-jnk edt-deleteShallow edt-par2win edt-archivedirectory
do
    if [ ! -d "$i" ]
    then
	git clone "https://github.com/edt11x/$i.git"
    fi
done
if [ ! -f "$HOME/.vimrc" ]
then
    cp -ax edt-jnk/vim/vimrc "$HOME/.vimrc"
fi
if [ ! -d "$HOME/.vim" ]
then
    cp -ax edt-jnk/vim/vim "$HOME/.vim"
fi
if [ -f edt-archivedirectory/archivedirectory ]
then
    cp -ax edt-archivedirectory/archivedirectory "$HOME/bin"
fi

cd $HOME/files/othersrc
if [ ! -d "vim-plug" ]
then
    git clone https://github.com/junegunn/vim-plug.git
fi

echo "DIR 01;36" > $HOME/.dir_colors
echo "DIR 01;36" > $HOME/.dircolors
# -q is quiet
# -F is plain string
grep -qF 'LS_COLORS=' $HOME/.bashrc || dircolors -b $HOME/.dir_colors >> $HOME/.bashrc
grep -qF 'alias cde=' $HOME/.bashrc || echo 'alias cde="cd $HOME/files/home/edt-env"' >> $HOME/.bashrc
grep -qF 'alias cdh=' $HOME/.bashrc || echo 'alias cdh="cd $HOME/files/home"' >> $HOME/.bashrc
grep -qF 'alias cdr=' $HOME/.bashrc || echo 'alias cdr="cd $HOME/files/work/Vertiv/realtek-switch-simulator"' >> $HOME/.bashrc
