#!/bin/bash
cd $HOME
mkdir -p bin
mkdir -p jnk
mkdir -p tmp
mkdir -p files/home
mkdir -p files/work
grep -qxF 'set -o vi' $HOME/.bashrc || echo 'set -o vi' >> ~/.bashrc
cd $HOME/files/home
git clone https://github.com/edt11x/edt-btok.git
git clone https://github.com/edt11x/edt-hp.git
git clone https://github.com/edt11x/edt-jnk.git
git clone https://github.com/edt11x/edt-deleteShallow.git
git clone https://github.com/edt11x/edt-par2win.git
git clone https://github.com/edt11x/edt-archivedirectory.git

